# Ordered list of active source identifiers for the SkyKeys scraper
# pipeline. Update this file to enable/disable adapters without touching
# application code.

sources:
  - planetkey
  - keys_for_steam
  - ggdeals
  - cheapshark
  - isthereanydeal
  - cdkeys
  - eneba
  - fanatical
  - gamivo
  - greenmangaming
