# Scraping configuration for eneba.
# TODO: Fill selectors based on the site's DOM structure and ensure they
# respect robots.txt rules and rate limits.

metadata:
  display_name: "Eneba"
  homepage: "https://www.example.com"
  default_currency: "EUR"

rate_limits:
  requests_per_minute: 4
  random_delay_seconds:
    min: 0.8
    max: 2.5

search:
  url_template: "https://www.example.com/search?q={query}"
  pagination:
    enabled: false
    max_pages: 1
  limits:
    max_items: 20

selectors:
  results: "TODO-CSS-SELECTOR"
  title: "TODO-CSS-SELECTOR"
  price_text: "TODO-CSS-SELECTOR"
  link: "TODO-CSS-SELECTOR"
  platform: "TODO-CSS-SELECTOR"
  region: "TODO-CSS-SELECTOR"

price_parsing:
  regex: "(?P<amount>[0-9]+(?:,[0-9]{2})?)\s*(?P<currency>[A-Z]{3})?"
  currency_fallback: "EUR"

flags:
  assume_fees_zero: true
  notes: "TODO: document quirks like VAT inclusion or regional locks."
